### ISSUE TITLE
Sending to ipython shell becomes very slow after some time

### ISSUE THREAD

**Issue by guibor** [jdtsmith/python-mls#6]
First, this is a great package and would potentially be super useful.

What is preventing me from using it, is that I noticed that sending statements from buffer to python shell was lagging after I started using this package. After turning it off everything was back to normal.

What information would be most helpful to debug this?

**Comment by jdtsmith** [comment]
I'm doubtful this has anything to do with python-mls.  The only thing python-mls changes in the python buffer is updating yank-excluded-properties so the `...`'s don't come across on yank.  How are you sending from buffer to shell?  Is this Python or iPython?

**Comment by guibor** [comment]
Hi! Sorry for the delay.

I use ipython. What becomes slow, is sending from buffer to ipython shell (using the `python-shell-buffer-substring` called from elpy `elpy-shell-send-statement-and-step`).

This is really consistent and it's enough for me to turn python-mls-mode off in the Python shell buffer for things to be fast again.

**Comment by jdtsmith** [comment]
Strange.  I still can't really see how this could be impacted by python-mls-mode.  Can you pare your configuration down to just python-mls (or better, start with `emacs -Q`), leaving out elpy, and give me a detailed step-by-step to reproduce the issue?  How slow is slow?  Also, what emacs version and OS?

**Comment by jdtsmith** [comment]
Is this a Windows system @guibor? I'm happy to look into this but would need substantially more information than you've provided thus far.  If it happens to you with emacs -Q and python-mls loaded (only), then that may require some investigation.

**Comment by jdtsmith** [comment]
No response, closing this for now.  If you can provide more information we can reopen.
