### ISSUE TITLE
avoid default mapping of python-mls-noblock-up/down-or-history to shift-up/down

### ISSUE THREAD

**Issue by pjj** [jdtsmith/python-mls#9]
The default keyboard bindings of the old windmove package use shift-arrows to select nearby windows.  python-mls-mode overwrites shift-up / shift-down. I want to keep using the windmove bindings and also python-mls-mode with my own keybindings for python-mls-noblock-up-or-history and python-mls-noblock-down-or-history.  More generally, is there an easy way to move some of the keybindings of python-mls-mode to an optional couple of lines during package configuration?

**Comment by jdtsmith** [comment]
Yeah I long ago set `windmove-default-keybindings` to  `'(super)`.  

I've just added a new customization `python-mls-multiline-history-modifier` which allows you to either disable this binding, or use another modifier (set), like `'(shift meta)` or `'(super)`.  Let me know how that works.   

For more custom bindings, you can also just use `define-key` to override them.

**Comment by pjj** [comment]
Thanks.  I'm now using the following config and things appear to work fine.
`(use-package python-mls
  :ensure t
  :config
  (setq python-mls-multiline-history-modifier '(super))
  (python-mls-setup))
`
